Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: "echo Hello"

  config.vm.define "server" do |server|
    server.vm.box = "centos/7"
    server.vm.hostname = "server"
    server.vm.provision "shell", path: "serverscript.sh"
    server.vm.network "private_network", ip: "192.168.1.10", virtualbox__intnet: "mynetwork"
  end

  config.vm.define "client1" do |client1|
    client1.vm.box = "centos/7"
    client1.vm.hostname = "client1"
    client1.vm.provision "shell", path: "client1script.sh"
    client1.vm.network "private_network", ip: "192.168.1.11", virtualbox__intnet: "mynetwork"
  end

  config.vm.define "client2" do |client2|
    client2.vm.box = "centos/7"
    client2.vm.hostname = "client2"
    client2.vm.provision "shell", path: "client2script.sh"
    client2.vm.network "private_network", ip: "192.168.1.12", virtualbox__intnet: "mynetwork"
  end
end