---
- hosts: all
  become: true
  tasks: 

  #yum-utils installeren
  - name: install yum-utils
    yum:
      name: yum-utils
      state: latest

  #Docker repository downloaden
  - name: Add repository Docker
    yum_repository:
      name: docker
      description: Docker YUM repo
      baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
      
  # Als docker geïnstalleerd is, deze dan verwijderen
  - name: Remove docker if installed from CentOS repo
    yum:
      name:
        - docker
        - docker-client
        - docker-client-latest
        - docker-common
        - docker-latest
        - docker-latest-logrotate
        - docker-logrotate
        - docker-engine
      state: removed

  - name: install Docker
    yum:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      state: latest

  - name: Add repository HashiCorp
    yum_repository:
      name: HashiCorp
      description: HashiCorp repo
      baseurl: https://rpm.releases.hashicorp.com/RHEL/$releasever/$basearch/stable

  - name: Install Consul
    yum:
      name: consul
      state: latest

  - name: Install Nomad
    yum:
      name: nomad
      state: latest


 # - name: start Docker
 #   service:
 #     name: docker
 #     state: started
 #     enabled: yes

 # - name: start consul
 #   service:
 #     name: consul
 #     state: started
 #     enabled: yes

 # - name: start nomad
 #   service:
 #     name: nomad
 #     state: started
 #     enabled: yes

#  - name: nomad server config
#    copy:
#      src: files/nomadserver.hcl
#      dest: /etc/nomad.d/nomad.hcl

#  - name: nomad client config
#    copy:
#      src: files/nomadclient.hcl
#      dest: /etc/nomad.d/nomad.hcl

#  - name: consul server config
#    copy:
#      src: files/consulserver.hcl
#     dest: /etc/consul.d/consul.hcl

#  - name: consul client config
#    copy:
#      src: files/consulclient.hcl
#      dest: /etc/consul.d/consul.hcl




 