- name: Configuring hashicorp repo
  get_url:
    url: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    dest: /etc/yum.repos.d/hashicorp.repo
    mode: 0644

- name: Install Consul
  yum:
    name: consul
    state: latest