# -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos/7"

  config.vm.define "server" do |server|
    server.vm.hostname = "server"
    server.vm.network "private_network", ip: "10.0.0.10"

    server.vm.provision "ansible_local" do |ansible|
      #ansible.inventory_path = "ansible/inventory/hosts"
      #ansible.config_file = "ansible/ansible.cfg"
      ansible.groups = {
        "servers" => ["server"],
        "clients" => ["client1","client2"]
      }
      ansible.host_vars = {
        "server" => {"ansible_connection" => "local",
                     "nomad_config_srcpath" => "files/nomadserver.hcl",
                     "consul_bind_addr_ip" => "10.0.0.10",
                     "consul_server_true" => "server = true",
                     "consul_bootstrap_1" => "bootstrap_expect=1",
                     "retry_join_client" => ""}
      }
      ansible.playbook = "ansible/playbook.yml"
    end
  end

  config.vm.define "client1" do |client1|
      client1.vm.hostname = "client1"
      client1.vm.network "private_network", ip: "10.0.0.11"

      client1.vm.provision "ansible_local" do |ansible|
      ansible.groups = {
        "servers" => ["server"],
        "clients" => ["client1","client2"]
      }
      ansible.host_vars = {
        "client1" => {"ansible_connection" => "local",
                      "nomad_config_srcpath" => "files/nomadclient.hcl",
                      "consul_bind_addr_ip" => "10.0.0.11",
                      "consul_server_true" => "server = false",
                      "consul_bootstrap_1" => "",
                      "retry_join_client" => "10.0.0.10"}
      }
      ansible.playbook = "ansible/playbook.yml"
    end
  end


  config.vm.define "client2" do |client2|
      client2.vm.hostname = "client2"
      client2.vm.network "private_network", ip: "10.0.0.12"

      client2.vm.provision "ansible_local" do |ansible|
      ansible.groups = {
        "servers" => ["server"],
        "clients" => ["client1","client2"]
      }
      ansible.host_vars = {
       "client2" => {"ansible_connection" => "local",
                      "nomad_config_srcpath" => "files/nomadclient.hcl",
                      "consul_bind_addr_ip" => "10.0.0.12",
                      "consul_server_true" => "server = false",
                      "consul_bootstrap_1" => "",
                      "retry_join_client" => "10.0.0.10"}
      }
      ansible.playbook = "ansible/playbook.yml"
    end
  end
end