# -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  #config.vbguest.auto_update = false
  config.vm.box = "centos/7"

  config.vm.define "server" do |server|
    server.vm.hostname = "server"
    server.vm.network "private_network", ip: "10.0.0.10"

    server.vm.provision "ansible_local" do |ansible|
      ansible.config_file = "ansible/ansible.cfg"
      ansible.playbook = "ansible/server.yml"
    end

  end

  config.vm.define "client1" do |client1|
      client1.vm.hostname = "client1"
      client1.vm.network "private_network", ip: "10.0.0.11"
  end

 config.vm.define "client2" do |client2|
      client2.vm.hostname = "client2"
      client2.vm.network "private_network", ip: "10.0.0.12"
  end
end